Need to fix failed tests in oagw when auth_disabled is false
  FAILED testing/e2e/modules/oagw/test_cors.py::test_cors_preflight_allowed_origin
  FAILED testing/e2e/modules/oagw/test_cors.py::test_cors_preflight_rejected_origin
  FAILED testing/e2e/modules/oagw/test_cors.py::test_cors_preflight_rejected_method
  FAILED testing/e2e/modules/oagw/test_cors.py::test_cors_preflight_rejected_header
  FAILED testing/e2e/modules/oagw/test_cors.py::test_cors_preflight_with_credentials

Signed-off-by: Roland From <rfedorov@linkentools.com>